USE [master]
GO

/****** Object:  Database [northwind]    Script Date: 1/20/2023 1:10:20 AM ******/
CREATE DATABASE [northwind]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'northwind', FILENAME = N'C:\Users\sergey\northwind.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [SECONDARY]  DEFAULT
( NAME = N'northwind_act', FILENAME = N'C:\Users\sergey\northwind_act.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'northwind_log', FILENAME = N'C:\Users\sergey\northwind_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [northwind].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [northwind] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [northwind] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [northwind] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [northwind] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [northwind] SET ARITHABORT OFF 
GO

ALTER DATABASE [northwind] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [northwind] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [northwind] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [northwind] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [northwind] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [northwind] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [northwind] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [northwind] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [northwind] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [northwind] SET  DISABLE_BROKER 
GO

ALTER DATABASE [northwind] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [northwind] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [northwind] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [northwind] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [northwind] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [northwind] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [northwind] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [northwind] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [northwind] SET  MULTI_USER 
GO

ALTER DATABASE [northwind] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [northwind] SET DB_CHAINING OFF 
GO

ALTER DATABASE [northwind] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [northwind] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [northwind] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [northwind] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [northwind] SET QUERY_STORE = OFF
GO

ALTER DATABASE [northwind] SET  READ_WRITE 
GO

